### ISSUE TITLE
how to run this code ?

### ISSUE THREAD

**Issue by mlotfi2005** [vinyll/flask-socketio-demo#1]
Hi,
Can you please show us how to run this code ?
thanks.

**Comment by vinyll** [comment]
The link in the _readme_ is broken.
Please visit http://vinyll.scopyleft.fr/socketio-with-gevent-using-flask/ to know how to run this code and for further details.

**Comment by vinyll** [comment]
updated readme accordingly

**Comment by mlotfi2005** [comment]
I don't see any update, where it say how to run it ?
Thanks.

**Comment by vinyll** [comment]
I changed the readme to insert the link I gave you (http://vinyll.scopyleft.fr/socketio-with-gevent-using-flask/).
You should have all the instructions over there.
